spring.application.name=event-api

# Security
spring.security.enabled=false

# Database
spring.datasource.url=jdbc:postgresql://localhost:5432/events
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.jooq.sql-dialect=postgres

# Kafka
spring.kafka.bootstrap-servers=localhost:9092

# Server
server.port=8080
